### ISSUE TITLE
 QSFS0.0.5 0-DB: protection of ZDBs 

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/quantum-storage#12]
move zdb instead of outright deleting it on zos...
so user dont lose data if payment isnt met. recover data safely if incidents happen

**Comment by LeeSmet** [comment]
An idea would be to make some 0-db namespace read only, so that we can keep it like this without decomissioning it completely for some time. However, as a user, you are admin on your namespace, so you could overwrite the read only mode again. An idea could be to have the 0-db admin (i.e. the node) move the namespace in read only, and only allow the db admin (not the namespace admin) to change that afterwards. Not sure if this is feasible.

@maxux any input or ideas?

**Comment by maxux** [comment]
What's the purpose of protected zdbs ?

**Comment by LeeSmet** [comment]
I imagine the most interesting usecase would be if a capacity pool runs out, so that there is time to move the data before it dissapears, as a pool might have multiple zdbs attached, which in turn causes the system to become irrepearable.

**Comment by maxux** [comment]
Latest changes on `zos` makes `0-db` running in admin protected mode.

There is a way to put the namespace in readonly mode: `NSSET [namespace] lock 1`.
This is only possible for admin (aka zos here) and the user cannot interfere on that. It seems that could be enough ?

**Comment by LeeSmet** [comment]
Lets go with this approach. We do need to see how long we will keep the data though. For now I propose we always move to read only for x amount of time after a 0-db gets decomissioned to keep the flow simple

**Comment by robvanmieghem** [comment]
deprecated since payments and decomissioning are handled differently on grid v3
