### ISSUE TITLE
SDK Manual - documentation: show how to use evdc etcd for QSFS config 

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/quantum-storage#3]
vdc will have etcd cluster. 

- [ ] on wiki
- [ ] on repo quantum storage

**Comment by xmonader** [comment]
any updates here? @gmachtel @weynandkuijpers ?

**Comment by scottyeager** [comment]
@gmachtel has updated the wiki to reflect the VDC hosted etcd option here: https://new.threefold.io/info/cloud#/cloud__threefold_filesystem

I am currently testing the latest releases of the QSFS stack in order to be able to document new features like time based persistence. My VDC etcd [didn't work](https://github.com/threefoldtech/js-sdk/issues/2859), so am working against a local etcd for now.

**Comment by xmonader** [comment]
@scottyeager for your problem, zstor will accept/use the provisioned etcds without problem https://github.com/etcd-io/etcd/issues/8458

**Comment by scottyeager** [comment]
QSFS will not be using etcd anymore, relying on the zdbs for metadata instead. See: https://github.com/threefoldtech/0-stor_v2/issues/41#

**Comment by xmonader** [comment]
> QSFS will not be using etcd anymore, relying on the zdbs for metadata instead. See: [threefoldtech/0-stor_v2#41](https://github.com/threefoldtech/0-stor_v2/issues/41)

this now can be closed indeed
